# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello_grpc.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10hello_grpc.proto\x12\nhello_grpc\x1a\x1fgoogle/protobuf/timestamp.proto\"9\n\x07Request\x12.\n\nrequest_ts\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\";\n\x08Response\x12/\n\x0bresponse_ts\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2H\n\x0bGRPCService\x12\x39\n\x0cGetTimestamp\x12\x13.hello_grpc.Request\x1a\x14.hello_grpc.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_grpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=65
  _globals['_REQUEST']._serialized_end=122
  _globals['_RESPONSE']._serialized_start=124
  _globals['_RESPONSE']._serialized_end=183
  _globals['_GRPCSERVICE']._serialized_start=185
  _globals['_GRPCSERVICE']._serialized_end=257
# @@protoc_insertion_point(module_scope)
